# Generated by Django 3.1.7 on 2021-12-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UPC_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_uid', models.CharField(max_length=50, verbose_name='账号')),
                ('u_password', models.CharField(max_length=50, verbose_name='密码')),
                ('u_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('u_type', models.BooleanField(default=False, verbose_name='是否是教师')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'UPC_User',
            },
        ),
    ]
