# Generated by Django 3.1.7 on 2021-12-10 10:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50, verbose_name='班级名称')),
                ('nianJ', models.CharField(max_length=10, verbose_name='年级')),
            ],
            options={
                'verbose_name': '班级管理',
                'verbose_name_plural': '班级管理',
                'db_table': 'ClassTable',
            },
        ),
        migrations.CreateModel(
            name='CollegeTable',
            fields=[
                ('college_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='院系号')),
                ('college_name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '院系管理',
                'verbose_name_plural': '院系管理',
                'db_table': 'CollegeTable',
            },
        ),
        migrations.CreateModel(
            name='CourseTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50, verbose_name='课程代码')),
                ('course_name', models.CharField(max_length=50, verbose_name='课程名称')),
                ('CourseNature', models.CharField(max_length=50, verbose_name='课程性质')),
                ('credit', models.CharField(max_length=50, verbose_name='学分')),
                ('time', models.CharField(max_length=50, verbose_name='上课时间')),
                ('adress', models.CharField(max_length=50, verbose_name='上课地点')),
            ],
            options={
                'verbose_name': '课程管理',
                'verbose_name_plural': '课程管理',
                'db_table': 'CourseTable',
            },
        ),
        migrations.CreateModel(
            name='JurisdictionTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsAddScore', models.BooleanField(default=False, verbose_name='是否可以录入成绩')),
                ('IsModify', models.BooleanField(default=False, verbose_name='是否可以修改学生信息')),
                ('IsCancel', models.BooleanField(default=False, verbose_name='是否可以管理违纪')),
                ('IsLeave', models.BooleanField(default=True, verbose_name='是否可以审核请假')),
                ('IsChoice', models.BooleanField(default=False, verbose_name='是否可以选课')),
            ],
            options={
                'verbose_name': '权限管理',
                'verbose_name_plural': '权限管理',
                'db_table': 'JurisdictionTable',
            },
        ),
        migrations.CreateModel(
            name='LeaveTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, verbose_name='学号/工号')),
                ('uname', models.CharField(max_length=50, verbose_name='姓名')),
                ('startTime', models.CharField(max_length=50, verbose_name='开始时间')),
                ('endtime', models.CharField(max_length=50, verbose_name='结束时间')),
                ('reason', models.CharField(max_length=500, verbose_name='请假原因')),
                ('isAgree', models.BooleanField(verbose_name='是否同意')),
                ('shtype', models.IntegerField(default=0, verbose_name='审核状态')),
                ('result', models.CharField(default='无', max_length=500, verbose_name='审核意见')),
                ('agreeTeacher', models.CharField(default='无', max_length=50, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '请假管理',
                'verbose_name_plural': '请假管理',
                'db_table': 'LeaveTable',
            },
        ),
        migrations.CreateModel(
            name='NoticeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '通知管理',
                'verbose_name_plural': '通知管理',
                'db_table': 'NoticeTable',
            },
        ),
        migrations.CreateModel(
            name='PunishmentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, verbose_name='学号/工号')),
                ('uname', models.CharField(max_length=50, verbose_name='姓名')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('reason', models.CharField(max_length=2000, verbose_name='违纪原因')),
                ('type', models.CharField(max_length=50, verbose_name='违纪类型')),
                ('examine', models.CharField(default='教务处', max_length=50, verbose_name='审核')),
                ('iscancel', models.BooleanField(default=False, verbose_name='是否取消')),
            ],
            options={
                'verbose_name': '违纪处分管理',
                'verbose_name_plural': '违纪处分管理',
                'db_table': 'PunishmentTable',
            },
        ),
        migrations.CreateModel(
            name='TeacherTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_id', models.CharField(max_length=50, verbose_name='工号')),
                ('tea_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=2, verbose_name='性别')),
                ('position', models.CharField(choices=[('1', '辅导员'), ('2', '教务处'), ('3', '教师')], max_length=3, verbose_name='职位')),
                ('tea_title', models.CharField(max_length=50, verbose_name='职称')),
                ('tea_email', models.CharField(max_length=100, verbose_name='电子邮件')),
                ('tea_phone', models.CharField(max_length=11, verbose_name='联系方式')),
                ('tea_AdmissionTime', models.DateTimeField(auto_now_add=True, verbose_name='入职时间')),
                ('tea_adress', models.CharField(max_length=100, verbose_name='家庭住址')),
                ('tea_birth', models.CharField(max_length=100, verbose_name='出生日期')),
                ('tea_nation', models.CharField(max_length=20, verbose_name='民族')),
                ('tea_PoliticalOutlook', models.CharField(max_length=20, verbose_name='政治面貌')),
                ('tea_IdNumber', models.CharField(max_length=18, verbose_name='身份证号')),
                ('tea_GraduateUniversity', models.CharField(max_length=50, verbose_name='毕业大学')),
                ('tea_education', models.CharField(max_length=50, verbose_name='学历')),
                ('tea_major', models.CharField(max_length=20, verbose_name='专业')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.collegetable')),
            ],
            options={
                'verbose_name': '教师信息管理',
                'verbose_name_plural': '教师信息管理',
                'db_table': 'TeacherTable',
            },
        ),
        migrations.CreateModel(
            name='StudentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=50, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('sex', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=2, verbose_name='性别')),
                ('stu_email', models.CharField(max_length=100, verbose_name='电子邮件')),
                ('stu_phone', models.CharField(max_length=11, verbose_name='联系方式')),
                ('stu_AdmissionTime', models.DateTimeField(auto_now_add=True, verbose_name='入学时间')),
                ('stu_adress', models.CharField(max_length=100, verbose_name='家庭住址')),
                ('stu_birth', models.CharField(max_length=100, verbose_name='出生日期')),
                ('stu_nation', models.CharField(max_length=20, verbose_name='民族')),
                ('stu_PoliticalOutlook', models.CharField(max_length=20, verbose_name='政治面貌')),
                ('stu_IdNumber', models.CharField(max_length=18, verbose_name='身份证号')),
                ('stu_graduating', models.CharField(max_length=50, verbose_name='毕业中学')),
                ('stu_SchoolSystem', models.CharField(default='全日制大专', max_length=20, verbose_name='学制')),
                ('stu_schoolYear', models.CharField(default='3年', max_length=20, verbose_name='学年')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.collegetable')),
                ('stu_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classtable', verbose_name='班级')),
            ],
            options={
                'verbose_name': '学生信息管理',
                'verbose_name_plural': '学生信息管理',
                'db_table': 'StudentTable',
            },
        ),
        migrations.CreateModel(
            name='OpenTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='学年')),
                ('semester', models.CharField(max_length=20, verbose_name='学期')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.coursetable', verbose_name='课程')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.teachertable', verbose_name='教师')),
            ],
            options={
                'verbose_name': '开课管理',
                'verbose_name_plural': '开课管理',
                'db_table': 'OpenTable',
            },
        ),
        migrations.AddField(
            model_name='classtable',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.collegetable'),
        ),
        migrations.CreateModel(
            name='ScoreTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('GradePoint', models.CharField(max_length=10, verbose_name='绩点')),
                ('open', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.opentable', verbose_name='开课标识号')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studenttable', verbose_name='学号')),
            ],
            options={
                'verbose_name': '选课管理',
                'verbose_name_plural': '选课管理',
                'db_table': 'ScoreTable',
                'unique_together': {('student', 'open')},
            },
        ),
    ]
